spring.application.name=nexboard

spring.datasource.url=jdbc:postgresql://localhost:5432/nexboard
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=4e6f77566572795365637265744b6579466f724a575423323032354e657842
jwt.expiration-ms=31536000000

# Debug logging
logging.level.org.springframework.security=DEBUG
logging.level.com.nexboard=DEBUG

spring.security.oauth2.client.registration.google.client-id=***REMOVED***
spring.security.oauth2.client.registration.google.client-secret=***REMOVED***
spring.security.oauth2.client.registration.google.scope=email,profile

spring.security.oauth2.client.registration.github.client-id=***REMOVED***
spring.security.oauth2.client.registration.github.client-secret=***REMOVED***
spring.security.oauth2.client.registration.github.scope=user:email

server.port=8080