package com.nexboard.nexboard.service;

import com.nexboard.nexboard.dto.NotificationResponseDto;
import com.nexboard.nexboard.entity.Employee;
import com.nexboard.nexboard.entity.Notification;
import com.nexboard.nexboard.entity.WorkflowTask;
import com.nexboard.nexboard.enums.NotificationType;
import com.nexboard.nexboard.repository.NotificationRepository;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.List;

@Service
public class NotificationService {

    private final NotificationRepository notificationRepository;

    public NotificationService(
            NotificationRepository notificationRepository) {
        this.notificationRepository = notificationRepository;
    }

    // Welcome notification created when an employee is onboarded.
    public void sendWelcomeEmployeeNotification(Employee employee) {

        if (notificationRepository.existsByEmployeeIdAndType(
                employee.getId(),
                NotificationType.WELCOME_EMPLOYEE)) {
            return;
        }

        createNotification(
                NotificationType.WELCOME_EMPLOYEE,
                "Welcome to NexBoard",
                "Welcome " + employee.getFirstName()
                        + ". Your onboarding path is now being prepared.",
                employee,
                null
        );
    }

    // Task assignment notification created for manual and template tasks.
    public void sendNewTaskAssignedNotification(WorkflowTask task) {

        createTaskNotificationIfMissing(
                NotificationType.NEW_TASK_ASSIGNED,
                "New onboarding task assigned",
                "Task " + task.getTaskName()
                        + " has been assigned with due date "
                        + task.getDueDate(),
                task
        );
    }

    // Overdue task notification generated by escalation scans.
    public void sendOverdueTaskNotification(WorkflowTask task) {

        createTaskNotificationIfMissing(
                NotificationType.OVERDUE_TASK,
                "Onboarding task overdue",
                "Task " + task.getTaskName()
                        + " is overdue for "
                        + task.getEmployee().getFirstName(),
                task
        );
    }

    // Completion notification created when all employee tasks are complete.
    public void sendCompletedOnboardingNotification(Employee employee) {

        if (notificationRepository.existsByEmployeeIdAndType(
                employee.getId(),
                NotificationType.COMPLETED_ONBOARDING)) {
            return;
        }

        createNotification(
                NotificationType.COMPLETED_ONBOARDING,
                "Onboarding completed",
                employee.getFirstName()
                        + " has completed onboarding.",
                employee,
                null
        );
    }

    public List<NotificationResponseDto> getAllNotifications() {

        return notificationRepository.findAll()
                .stream()
                .map(this::mapToResponse)
                .toList();
    }

    public List<NotificationResponseDto> getNotificationsByEmployee(
            Long employeeId) {

        return notificationRepository
                .findByEmployeeIdOrderByCreatedAtDesc(employeeId)
                .stream()
                .map(this::mapToResponse)
                .toList();
    }

    public NotificationResponseDto markNotificationAsRead(
            Long notificationId) {

        Notification notification =
                notificationRepository.findById(notificationId)
                        .orElseThrow(() ->
                                new RuntimeException("Notification not found"));

        notification.setRead(true);

        return mapToResponse(
                notificationRepository.save(notification));
    }

    private void createTaskNotificationIfMissing(
            NotificationType type,
            String title,
            String message,
            WorkflowTask task) {

        if (notificationRepository.existsByWorkflowTaskIdAndType(
                task.getId(),
                type)) {
            return;
        }

        createNotification(
                type,
                title,
                message,
                task.getEmployee(),
                task
        );
    }

    private void createNotification(
            NotificationType type,
            String title,
            String message,
            Employee employee,
            WorkflowTask task) {

        Notification notification = new Notification();
        notification.setType(type);
        notification.setTitle(title);
        notification.setMessage(message);
        notification.setRead(false);
        notification.setCreatedAt(LocalDateTime.now());
        notification.setEmployee(employee);
        notification.setWorkflowTask(task);

        notificationRepository.save(notification);
    }

    private NotificationResponseDto mapToResponse(
            Notification notification) {

        String employeeName = "";
        if (notification.getEmployee() != null) {
            employeeName = notification.getEmployee().getFirstName()
                    + " "
                    + notification.getEmployee().getLastName();
        }

        String taskName = "";
        if (notification.getWorkflowTask() != null) {
            taskName = notification.getWorkflowTask().getTaskName();
        }

        return new NotificationResponseDto(
                notification.getId(),
                notification.getType().name(),
                notification.getTitle(),
                notification.getMessage(),
                notification.isRead(),
                employeeName,
                taskName,
                notification.getCreatedAt().toString()
        );
    }
}
