package com.nexboard.nexboard.enums;

// Notification event types generated by onboarding workflows.
public enum NotificationType {

    NEW_TASK_ASSIGNED,
    OVERDUE_TASK,
    COMPLETED_ONBOARDING,
    WELCOME_EMPLOYEE
}
